Repository NICE-practice/bmstu_teamdev_shelter, pull requests merged in 2023-04, with the labels that each got.

#48 47 edit workflow
  .github/workflows/main.yml
  db/create_db_shelter.sql
  db/generate_db_shelter.py
  db/install_db_shelter.bat
  db/install_db_shelter.sh
  src/server/models/models.js
Labels: database, github actions

#51 18 jwt authorization backend
  src/server/controllers/userController.js
  src/server/errors/ApiError.js
  src/server/index.js
  src/server/middleware/ErrorHandlingMiddleware.js
  src/server/middleware/authMiddleware.js
  src/server/middleware/checkRoleMiddleware.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/index.js
  src/server/routes/userRouter.js
Labels: backend

#52 #19 add: controller and router for animal
  src/server/controllers/animalController.js
  src/server/routes/animalRouter.js
  src/server/routes/index.js
Labels: backend

#55 closes 53 api for donations
  src/server/controllers/donationController.js
  src/server/routes/donationRouter.js
  src/server/routes/index.js
Labels: backend

#56 closes #54 add: router and controller for infoShelter
  src/server/controllers/infoShelterController.js
  src/server/routes/index.js
  src/server/routes/infoShelterRouter.js
Labels: backend

#57 closes #21 add: router and controller for message
  src/server/controllers/messageController.js
  src/server/routes/index.js
  src/server/routes/messageRouter.js
Labels: backend

#59 closes #58 set linter
  .vscode/settings.json
  src/server/.eslintrc.json
  src/server/controllers/animalController.js
  src/server/controllers/donationController.js
  src/server/controllers/infoShelterController.js
  src/server/controllers/messageController.js
  src/server/controllers/userController.js
  src/server/db.js
  src/server/errors/ApiError.js
  src/server/index.js
  src/server/middleware/ErrorHandlingMiddleware.js
  src/server/middleware/authMiddleware.js
  src/server/middleware/checkRoleMiddleware.js
  src/server/models/animalDTO.js
  src/server/models/animalVaccinationDTO.js
  src/server/models/donationDTO.js
  src/server/models/infoShelterDTO.js
  src/server/models/messageDTO.js
  src/server/models/modelsORM.js
  src/server/package-lock.json
  src/server/package.json
  src/server/pretierrc.config.js
  src/server/routes/animalRouter.js
  src/server/routes/donationRouter.js
  src/server/routes/infoShelterRouter.js
  src/server/routes/messageRouter.js
  src/server/routes/userRouter.js
Labels: backend

#68 67 csv for db
  db/data/animal_x_vaccinations.csv
  db/data/animals copy.csv
  db/data/animals.csv
  db/data/dict_privileges.csv
  db/data/donations.csv
  db/data/info_shelters.csv
  db/data/messages.csv
  db/data/user_shelters.csv
  db/data/vaccinations.csv
  db/filling_db_shelter.sql
  db/generate_db_csv.py
  db/generate_db_shelter.py
  db/insert/breed.txt
  db/insert/breed_cat.txt
  db/insert/breed_dog.txt
  db/insert/history_animal.txt
  db/insert/name_m.txt
  db/insert/name_w.txt
  db/insert/text_message.txt
  db/insert/vaccination.txt
  db/install_db_shelter.bat
  db/install_db_shelter.sh
Labels: database

#69 closes #25 set routes
  .gitignore
  src/client/package-lock.json
  src/client/package.json
  src/client/public/favicon.ico
  src/client/public/index.html
  src/client/public/logo192.png
  src/client/public/logo512.png
  src/client/public/manifest.json
  src/client/public/robots.txt
  src/client/src/App.css
  src/client/src/App.js
  src/client/src/App.test.js
  src/client/src/conponents/AppRouter.js
  src/client/src/index.css
  src/client/src/index.js
  src/client/src/logo.svg
  src/client/src/pages/Auth.js
  src/client/src/pages/Contact.js
  src/client/src/pages/Home.js
  src/client/src/pages/Pets.js
  src/client/src/reportWebVitals.js
  src/client/src/routes.js
  src/client/src/setupTests.js
Labels: frontend

#70 closes #60 add: unit test for animals api
  src/server/index.js
  src/server/package-lock.json
  src/server/package.json
  src/server/tests/unit_tests/animal.test.js
  src/server/tests/unit_tests/data_for_tests.js
  src/server/tests/unit_tests/tokens_for_tests.js
Labels: backend, testing

#71 closes #62 unit tests for infoshelter api
  src/server/tests/unit_tests/animal.test.js
  src/server/tests/unit_tests/data_for_tests.js
  src/server/tests/unit_tests/infoShelter.test.js
Labels: backend, testing

#72 closes #61 add tests for donation API, add error throwing in controller
  src/server/controllers/donationController.js
  src/server/tests/unit_tests/data_for_tests.js
  src/server/tests/unit_tests/donation.test.js
Labels: backend, testing

#73 closes #64 add: tests for user api
  src/server/controllers/userController.js
  src/server/tests/unit_tests/user.test.js
Labels: frontend, testing

#74 closes #63 add: tests for message api
  src/server/tests/unit_tests/data_for_tests.js
  src/server/tests/unit_tests/message.test.js
Labels: backend, testing

#75 closes #27 create petcard and personcard component
  src/client/src/conponents/PersonCard.js
  src/client/src/conponents/PetCard.js
  src/client/src/img/job.jpg
  src/client/src/style/Home.css
Labels: frontend

#76 close #31 create footer
  src/client/.eslintrc.json
  src/client/src/App.js
  src/client/src/conponents/Footer.js
  src/client/src/http/index.js
  src/client/src/http/shelterInfoApi.js
  src/client/src/img/cat2.png
  src/client/src/index.js
  src/client/src/store/ShelterInfoStore.js
  src/client/src/style/Home.css
Labels: frontend

#81 closes #79 fix: syntax errors
  src/server/.eslintrc.json
  src/server/pretierr.config.js
  src/server/pretierrc.config.js
  src/server/tests/unit_tests/animal.test.js
  src/server/tests/unit_tests/donation.test.js
  src/server/tests/unit_tests/infoShelter.test.js
  src/server/tests/unit_tests/message.test.js
  src/server/tests/unit_tests/tokens_for_tests.js
  src/server/tests/unit_tests/user.test.js
Labels: backend, refactoring

#82 Merge #78 add tests linter cicd
  .github/workflows/main.yml
Labels: github actions

#83 closes #50 add functions for jwt authorization
  src/client/src/http/index.js
  src/client/src/http/userApi.js
Labels: frontend

#84 closes #35 create authorization page
  src/client/package.json
  src/client/src/App.js
  src/client/src/conponents/AppRouter.js
  src/client/src/img/sign.jpg
  src/client/src/index.js
  src/client/src/pages/Auth.js
  src/client/src/pages/ContentManager.js
  src/client/src/pages/Operator.js
  src/client/src/routes.js
  src/client/src/store/UserStore.js
  src/client/src/style/Auth.css
Labels: frontend

#85 closes #26 add website menu and css styles
  src/client/package-lock.json
  src/client/src/conponents/Menu.js
  src/client/src/pages/Pets.js
  src/client/src/style/Home.css
Labels: frontend

#86 closes #42 add requests for messages
  src/client/src/http/messageApi.js
Labels: frontend

#88 closes #87 add field in get
  src/server/controllers/animalController.js
  src/server/controllers/messageController.js
  src/server/tests/unit_tests/animal.test.js
  src/server/tests/unit_tests/message.test.js
Labels: backend

#89 closes #44 add request for donation
  src/client/src/http/donateApi.js
Labels: frontend

#90 closes #29 add css styles,image,donation form and m
  src/client/src/conponents/DonateForm.js
  src/client/src/conponents/DonateModal.js
  src/client/src/img/close.svg
  src/client/src/img/dog2.png
  src/client/src/pages/Home.js
  src/client/src/style/Home.css
Labels: frontend

#91 closes #33 add form for messages and css file
  src/client/src/conponents/FormContact.js
  src/client/src/pages/Contact.js
  src/client/src/style/Contact.css
Labels: frontend

#92 closes #34 create contact page
  src/client/src/conponents/HeaderContact.js
  src/client/src/conponents/PersonCard.js
  src/client/src/conponents/Persons.js
  src/client/src/img/dogmain.jpg
  src/client/src/img/lead.jpg
  src/client/src/img/owner.jpg
  src/client/src/pages/Contact.js
  src/client/src/style/Contact.css
Labels: frontend

#93 closes #65 swagger documentation for backend
  src/server/.eslintrc.json
  src/server/controllers/messageController.js
  src/server/docs/backend_swagger.json
  src/server/docs/backend_swagger.yaml
  src/server/index.js
  src/server/middleware/ErrorHandlingMiddleware.js
  src/server/package-lock.json
  src/server/package.json
Labels: documentation, backend

#94 closes #40 create operator page
  src/client/src/conponents/ListMessage.js
  src/client/src/conponents/MessageCard.js
  src/client/src/conponents/Pages.js
  src/client/src/img/mes.jpg
  src/client/src/index.js
  src/client/src/pages/Operator.js
  src/client/src/store/MessageStore.js
  src/client/src/style/Message.css
Labels: frontend

#95 closes #36 add full pet card and css style
  src/client/src/conponents/CardPet.js
  src/client/src/style/Pets.css
Labels: frontend

#98 closes #97 update animalcount and add filtration
  src/server/controllers/animalController.js
Labels: backend

#96 closes #80 fix workflow
  .github/workflows/main.yml
Labels: github actions

#99 closes #41 add requests for pets
  src/client/src/http/petsApi.js
Labels: frontend

#100 closes #38 create filter for pets
  src/client/src/conponents/FindBlock.js
  src/client/src/index.js
  src/client/src/pages/Pets.js
  src/client/src/store/PetStore.js
  src/client/src/style/Pets.css
Labels: frontend

#101 closes #37 add component for pet cards page, cards page and styles
  src/client/src/App.js
  src/client/src/conponents/HeaderContact.js
  src/client/src/conponents/ListPets.js
  src/client/src/conponents/Menu.js
  src/client/src/conponents/PagesPets.js
  src/client/src/conponents/PetCard.js
  src/client/src/pages/Home.js
  src/client/src/pages/Pets.js
  src/client/src/style/Home.css
  src/client/src/style/Pets.css
Labels: frontend

#102 closes #28 add slider pets and styles css
  src/client/src/conponents/PetCard.js
  src/client/src/conponents/SliderPet.js
  src/client/src/pages/Home.js
  src/client/src/style/Home.css
Labels: frontend

#103 closes #30 create game animation cat
  src/client/src/conponents/PetGame.js
  src/client/src/img/care1.jpg
  src/client/src/img/cateat.jpg
  src/client/src/img/catgame.jpg
  src/client/src/img/cathappy.jpg
  src/client/src/img/catset.jpg
  src/client/src/img/eat.jpg
  src/client/src/img/toy.jpg
  src/client/src/pages/Home.js
  src/client/src/style/Home.css
Labels: frontend

#105 closes #39 create form for add update pet and vaccination
  src/client/src/conponents/AddPetModal.js
  src/client/src/conponents/AddVaccinationModal.js
  src/client/src/conponents/PetFormUpdate.js
  src/client/src/index.js
  src/client/src/store/VaccinationStore.js
  src/client/src/style/Pets.css
  src/server/models/animalVaccinationDTO.js
Labels: frontend

#107 closes #106 add image, styles,component and content manager page
  src/client/package-lock.json
  src/client/package.json
  src/client/src/conponents/AddPetModal.js
  src/client/src/conponents/AddVaccinationModal.js
  src/client/src/conponents/CardPet.js
  src/client/src/conponents/DeleteModal.js
  src/client/src/conponents/PetFormUpdate.js
  src/client/src/img/dog.jpg
  src/client/src/img/edit.svg
  src/client/src/pages/Auth.js
  src/client/src/pages/ContentManager.js
  src/client/src/store/PetStore.js
  src/client/src/style/Pets.css
Labels: frontend

#110 closes #109 create form validation and error handling
  src/client/src/conponents/AddPetModal.js
  src/client/src/conponents/AddVaccinationModal.js
  src/client/src/conponents/DonateForm.js
  src/client/src/conponents/FormContact.js
  src/client/src/conponents/ListPets.js
  src/client/src/conponents/PetFormUpdate.js
  src/client/src/pages/Auth.js
  src/client/src/pages/Pets.js
  src/client/src/style/Contact.css
  src/client/src/style/Home.css
  src/client/src/style/Pets.css
Labels: frontend
